// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/manifest.v1/estafette_trigger_release_action.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "protos/manifest.v1/EstafetteTriggerReleaseAction.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - EstafetteTriggerReleaseActionRoot

@implementation EstafetteTriggerReleaseActionRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - EstafetteTriggerReleaseActionRoot_FileDescriptor

static GPBFileDescriptor *EstafetteTriggerReleaseActionRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"manifest.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - EstafetteTriggerReleaseAction

@implementation EstafetteTriggerReleaseAction

@dynamic target;
@dynamic action;
@dynamic version;

typedef struct EstafetteTriggerReleaseAction__storage_ {
  uint32_t _has_storage_[1];
  NSString *target;
  NSString *action;
  NSString *version;
} EstafetteTriggerReleaseAction__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "target",
        .dataTypeSpecific.className = NULL,
        .number = EstafetteTriggerReleaseAction_FieldNumber_Target,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(EstafetteTriggerReleaseAction__storage_, target),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "action",
        .dataTypeSpecific.className = NULL,
        .number = EstafetteTriggerReleaseAction_FieldNumber_Action,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(EstafetteTriggerReleaseAction__storage_, action),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = EstafetteTriggerReleaseAction_FieldNumber_Version,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(EstafetteTriggerReleaseAction__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[EstafetteTriggerReleaseAction class]
                                     rootClass:[EstafetteTriggerReleaseActionRoot class]
                                          file:EstafetteTriggerReleaseActionRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(EstafetteTriggerReleaseAction__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
