// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/build_version_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BuildVersionConfigRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BuildVersionConfigRoot : GPBRootObject
@end

#pragma mark - BuildVersionConfig

typedef GPB_ENUM(BuildVersionConfig_FieldNumber) {
  BuildVersionConfig_FieldNumber_Version = 1,
  BuildVersionConfig_FieldNumber_Major = 2,
  BuildVersionConfig_FieldNumber_Minor = 3,
  BuildVersionConfig_FieldNumber_Patch = 4,
  BuildVersionConfig_FieldNumber_Label = 5,
  BuildVersionConfig_FieldNumber_AutoIncrement = 6,
};

@interface BuildVersionConfig : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@property(nonatomic, readwrite) int64_t major;

@property(nonatomic, readwrite) int64_t minor;

@property(nonatomic, readwrite, copy, null_resettable) NSString *patch;

@property(nonatomic, readwrite, copy, null_resettable) NSString *label;

@property(nonatomic, readwrite) int64_t autoIncrement;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
