// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/ci_server_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "contracts.v1/CiServerConfig.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - CiServerConfigRoot

@implementation CiServerConfigRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - CiServerConfigRoot_FileDescriptor

static GPBFileDescriptor *CiServerConfigRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - CIServerConfig

@implementation CIServerConfig

@dynamic baseURL;
@dynamic builderEventsURL;
@dynamic postLogsURL;
@dynamic apiKey;

typedef struct CIServerConfig__storage_ {
  uint32_t _has_storage_[1];
  NSString *baseURL;
  NSString *builderEventsURL;
  NSString *postLogsURL;
  NSString *apiKey;
} CIServerConfig__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "baseURL",
        .dataTypeSpecific.className = NULL,
        .number = CIServerConfig_FieldNumber_BaseURL,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CIServerConfig__storage_, baseURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "builderEventsURL",
        .dataTypeSpecific.className = NULL,
        .number = CIServerConfig_FieldNumber_BuilderEventsURL,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CIServerConfig__storage_, builderEventsURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "postLogsURL",
        .dataTypeSpecific.className = NULL,
        .number = CIServerConfig_FieldNumber_PostLogsURL,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CIServerConfig__storage_, postLogsURL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "apiKey",
        .dataTypeSpecific.className = NULL,
        .number = CIServerConfig_FieldNumber_ApiKey,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CIServerConfig__storage_, apiKey),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CIServerConfig class]
                                     rootClass:[CiServerConfigRoot class]
                                          file:CiServerConfigRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CIServerConfig__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\004\241!!\000\002\007\246\241!!\000\003\004\244\241!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
