// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/git_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "contracts.v1/GitConfig.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GitConfigRoot

@implementation GitConfigRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - GitConfigRoot_FileDescriptor

static GPBFileDescriptor *GitConfigRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GitConfig

@implementation GitConfig

@dynamic repoSource;
@dynamic repoOwner;
@dynamic repoName;
@dynamic repoBranch;
@dynamic repoRevision;

typedef struct GitConfig__storage_ {
  uint32_t _has_storage_[1];
  NSString *repoSource;
  NSString *repoOwner;
  NSString *repoName;
  NSString *repoBranch;
  NSString *repoRevision;
} GitConfig__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "repoSource",
        .dataTypeSpecific.className = NULL,
        .number = GitConfig_FieldNumber_RepoSource,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GitConfig__storage_, repoSource),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "repoOwner",
        .dataTypeSpecific.className = NULL,
        .number = GitConfig_FieldNumber_RepoOwner,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GitConfig__storage_, repoOwner),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "repoName",
        .dataTypeSpecific.className = NULL,
        .number = GitConfig_FieldNumber_RepoName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GitConfig__storage_, repoName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "repoBranch",
        .dataTypeSpecific.className = NULL,
        .number = GitConfig_FieldNumber_RepoBranch,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GitConfig__storage_, repoBranch),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "repoRevision",
        .dataTypeSpecific.className = NULL,
        .number = GitConfig_FieldNumber_RepoRevision,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GitConfig__storage_, repoRevision),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GitConfig class]
                                     rootClass:[GitConfigRoot class]
                                          file:GitConfigRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GitConfig__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
