// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contracts.v1/trusted_image_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TrustedImageConfigRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TrustedImageConfigRoot : GPBRootObject
@end

#pragma mark - TrustedImageConfig

typedef GPB_ENUM(TrustedImageConfig_FieldNumber) {
  TrustedImageConfig_FieldNumber_ImagePath = 1,
  TrustedImageConfig_FieldNumber_RunPrivileged = 2,
  TrustedImageConfig_FieldNumber_RunDocker = 3,
  TrustedImageConfig_FieldNumber_AllowCommands = 4,
  TrustedImageConfig_FieldNumber_InjectedCredentialTypesArray = 5,
};

@interface TrustedImageConfig : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *imagePath;

@property(nonatomic, readwrite) BOOL runPrivileged;

@property(nonatomic, readwrite) BOOL runDocker;

@property(nonatomic, readwrite) BOOL allowCommands;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *injectedCredentialTypesArray;
/** The number of items in @c injectedCredentialTypesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger injectedCredentialTypesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
