// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/build_log_line.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "estafette/ci/contracts/v1/BuildLogLine.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - BuildLogLineRoot

@implementation BuildLogLineRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - BuildLogLineRoot_FileDescriptor

static GPBFileDescriptor *BuildLogLineRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"estafette.ci.contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - BuildLogLine

@implementation BuildLogLine

@dynamic lineNumber;
@dynamic hasTimestampTime, timestampTime;
@dynamic streamType;
@dynamic text;

typedef struct BuildLogLine__storage_ {
  uint32_t _has_storage_[1];
  GPBTimestamp *timestampTime;
  NSString *streamType;
  NSString *text;
  int64_t lineNumber;
} BuildLogLine__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "lineNumber",
        .dataTypeSpecific.className = NULL,
        .number = BuildLogLine_FieldNumber_LineNumber,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(BuildLogLine__storage_, lineNumber),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "timestampTime",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBTimestamp),
        .number = BuildLogLine_FieldNumber_TimestampTime,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(BuildLogLine__storage_, timestampTime),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "streamType",
        .dataTypeSpecific.className = NULL,
        .number = BuildLogLine_FieldNumber_StreamType,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(BuildLogLine__storage_, streamType),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "text",
        .dataTypeSpecific.className = NULL,
        .number = BuildLogLine_FieldNumber_Text,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(BuildLogLine__storage_, text),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[BuildLogLine class]
                                     rootClass:[BuildLogLineRoot class]
                                          file:BuildLogLineRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(BuildLogLine__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
