// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/release.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EstafetteEvent;
@class GPBDuration;
@class GPBTimestamp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ReleaseRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ReleaseRoot : GPBRootObject
@end

#pragma mark - Release

typedef GPB_ENUM(Release_FieldNumber) {
  Release_FieldNumber_Name = 1,
  Release_FieldNumber_Action = 2,
  Release_FieldNumber_Id_p = 3,
  Release_FieldNumber_RepoSource = 4,
  Release_FieldNumber_RepoOwner = 5,
  Release_FieldNumber_ReleaseVersion = 6,
  Release_FieldNumber_ReleaseStatus = 7,
  Release_FieldNumber_EventsArray = 8,
  Release_FieldNumber_InsertedAtTime = 9,
  Release_FieldNumber_UpdatedAtTime = 10,
  Release_FieldNumber_Duration = 11,
};

@interface Release : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *action;

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *repoSource;

@property(nonatomic, readwrite, copy, null_resettable) NSString *repoOwner;

@property(nonatomic, readwrite, copy, null_resettable) NSString *releaseVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *releaseStatus;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EstafetteEvent*> *eventsArray;
/** The number of items in @c eventsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger eventsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *insertedAtTime;
/** Test to see if @c insertedAtTime has been set. */
@property(nonatomic, readwrite) BOOL hasInsertedAtTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *updatedAtTime;
/** Test to see if @c updatedAtTime has been set. */
@property(nonatomic, readwrite) BOOL hasUpdatedAtTime;

@property(nonatomic, readwrite, strong, null_resettable) GPBDuration *duration;
/** Test to see if @c duration has been set. */
@property(nonatomic, readwrite) BOOL hasDuration;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
