// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: estafette/ci/contracts/v1/release_params_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "estafette/ci/contracts/v1/ReleaseParamsConfig.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ReleaseParamsConfigRoot

@implementation ReleaseParamsConfigRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ReleaseParamsConfigRoot_FileDescriptor

static GPBFileDescriptor *ReleaseParamsConfigRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"estafette.ci.contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ReleaseParamsConfig

@implementation ReleaseParamsConfig

@dynamic releaseName;
@dynamic releaseId;
@dynamic releaseAction;
@dynamic triggeredBy;

typedef struct ReleaseParamsConfig__storage_ {
  uint32_t _has_storage_[1];
  NSString *releaseName;
  NSString *releaseAction;
  NSString *triggeredBy;
  int64_t releaseId;
} ReleaseParamsConfig__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "releaseName",
        .dataTypeSpecific.className = NULL,
        .number = ReleaseParamsConfig_FieldNumber_ReleaseName,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ReleaseParamsConfig__storage_, releaseName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "releaseId",
        .dataTypeSpecific.className = NULL,
        .number = ReleaseParamsConfig_FieldNumber_ReleaseId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ReleaseParamsConfig__storage_, releaseId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "releaseAction",
        .dataTypeSpecific.className = NULL,
        .number = ReleaseParamsConfig_FieldNumber_ReleaseAction,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ReleaseParamsConfig__storage_, releaseAction),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "triggeredBy",
        .dataTypeSpecific.className = NULL,
        .number = ReleaseParamsConfig_FieldNumber_TriggeredBy,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ReleaseParamsConfig__storage_, triggeredBy),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ReleaseParamsConfig class]
                                     rootClass:[ReleaseParamsConfigRoot class]
                                          file:ReleaseParamsConfigRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ReleaseParamsConfig__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
