// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/contracts.v1/build_log_line.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBTimestamp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BuildLogLineRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BuildLogLineRoot : GPBRootObject
@end

#pragma mark - BuildLogLine

typedef GPB_ENUM(BuildLogLine_FieldNumber) {
  BuildLogLine_FieldNumber_LineNumber = 1,
  BuildLogLine_FieldNumber_Timestamp = 2,
  BuildLogLine_FieldNumber_StreamType = 3,
  BuildLogLine_FieldNumber_Text = 4,
};

@interface BuildLogLine : GPBMessage

@property(nonatomic, readwrite) int64_t lineNumber;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

@property(nonatomic, readwrite, copy, null_resettable) NSString *streamType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
