// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/contracts.v1/release_target.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "protos/contracts.v1/ReleaseTarget.pbobjc.h"
#import "protos/contracts.v1/Release.pbobjc.h"
#import "protos/manifest.v1/EstafetteReleaseAction.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ReleaseTargetRoot

@implementation ReleaseTargetRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - ReleaseTargetRoot_FileDescriptor

static GPBFileDescriptor *ReleaseTargetRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ReleaseTarget

@implementation ReleaseTarget

@dynamic name;
@dynamic actionsArray, actionsArray_Count;
@dynamic activeReleasesArray, activeReleasesArray_Count;

typedef struct ReleaseTarget__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSMutableArray *actionsArray;
  NSMutableArray *activeReleasesArray;
} ReleaseTarget__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = ReleaseTarget_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ReleaseTarget__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "actionsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(EstafetteReleaseAction),
        .number = ReleaseTarget_FieldNumber_ActionsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ReleaseTarget__storage_, actionsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "activeReleasesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Release),
        .number = ReleaseTarget_FieldNumber_ActiveReleasesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ReleaseTarget__storage_, activeReleasesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ReleaseTarget class]
                                     rootClass:[ReleaseTargetRoot class]
                                          file:ReleaseTargetRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ReleaseTarget__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
