// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/contracts.v1/tail_log_line.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "protos/contracts.v1/TailLogLine.pbobjc.h"
#import "protos/contracts.v1/BuildLogLine.pbobjc.h"
#import "protos/contracts.v1/BuildLogStepDockerImage.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TailLogLineRoot

@implementation TailLogLineRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - TailLogLineRoot_FileDescriptor

static GPBFileDescriptor *TailLogLineRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - TailLogLine

@implementation TailLogLine

@dynamic step;
@dynamic hasLogLine, logLine;
@dynamic hasImage, image;
@dynamic hasDuration, duration;
@dynamic exitCode;
@dynamic status;
@dynamic autoInjected;

typedef struct TailLogLine__storage_ {
  uint32_t _has_storage_[1];
  NSString *step;
  BuildLogLine *logLine;
  BuildLogStepDockerImage *image;
  GPBDuration *duration;
  NSString *status;
  int64_t exitCode;
} TailLogLine__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "step",
        .dataTypeSpecific.className = NULL,
        .number = TailLogLine_FieldNumber_Step,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TailLogLine__storage_, step),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "logLine",
        .dataTypeSpecific.className = GPBStringifySymbol(BuildLogLine),
        .number = TailLogLine_FieldNumber_LogLine,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(TailLogLine__storage_, logLine),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "image",
        .dataTypeSpecific.className = GPBStringifySymbol(BuildLogStepDockerImage),
        .number = TailLogLine_FieldNumber_Image,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(TailLogLine__storage_, image),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "duration",
        .dataTypeSpecific.className = GPBStringifySymbol(GPBDuration),
        .number = TailLogLine_FieldNumber_Duration,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(TailLogLine__storage_, duration),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "exitCode",
        .dataTypeSpecific.className = NULL,
        .number = TailLogLine_FieldNumber_ExitCode,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(TailLogLine__storage_, exitCode),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = TailLogLine_FieldNumber_Status,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(TailLogLine__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "autoInjected",
        .dataTypeSpecific.className = NULL,
        .number = TailLogLine_FieldNumber_AutoInjected,
        .hasIndex = 6,
        .offset = 7,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TailLogLine class]
                                     rootClass:[TailLogLineRoot class]
                                          file:TailLogLineRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TailLogLine__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
