// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/contracts.v1/trusted_image_config.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "protos/contracts.v1/TrustedImageConfig.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - TrustedImageConfigRoot

@implementation TrustedImageConfigRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - TrustedImageConfigRoot_FileDescriptor

static GPBFileDescriptor *TrustedImageConfigRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"contracts.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - TrustedImageConfig

@implementation TrustedImageConfig

@dynamic imagePath;
@dynamic runPrivileged;
@dynamic runDocker;
@dynamic allowCommands;
@dynamic injectedCredentialTypesArray, injectedCredentialTypesArray_Count;

typedef struct TrustedImageConfig__storage_ {
  uint32_t _has_storage_[1];
  NSString *imagePath;
  NSMutableArray *injectedCredentialTypesArray;
} TrustedImageConfig__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "imagePath",
        .dataTypeSpecific.className = NULL,
        .number = TrustedImageConfig_FieldNumber_ImagePath,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(TrustedImageConfig__storage_, imagePath),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "runPrivileged",
        .dataTypeSpecific.className = NULL,
        .number = TrustedImageConfig_FieldNumber_RunPrivileged,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "runDocker",
        .dataTypeSpecific.className = NULL,
        .number = TrustedImageConfig_FieldNumber_RunDocker,
        .hasIndex = 3,
        .offset = 4,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "allowCommands",
        .dataTypeSpecific.className = NULL,
        .number = TrustedImageConfig_FieldNumber_AllowCommands,
        .hasIndex = 5,
        .offset = 6,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "injectedCredentialTypesArray",
        .dataTypeSpecific.className = NULL,
        .number = TrustedImageConfig_FieldNumber_InjectedCredentialTypesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(TrustedImageConfig__storage_, injectedCredentialTypesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[TrustedImageConfig class]
                                     rootClass:[TrustedImageConfigRoot class]
                                          file:TrustedImageConfigRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(TrustedImageConfig__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
