// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_manifest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EstafetteBuilder;
@class EstafetteRelease;
@class EstafetteStage;
@class EstafetteTrigger;
@class EstafetteVersion;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EstafetteManifestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EstafetteManifestRoot : GPBRootObject
@end

#pragma mark - EstafetteManifest

typedef GPB_ENUM(EstafetteManifest_FieldNumber) {
  EstafetteManifest_FieldNumber_Builder = 1,
  EstafetteManifest_FieldNumber_Labels = 2,
  EstafetteManifest_FieldNumber_Version = 3,
  EstafetteManifest_FieldNumber_GlobalEnvVars = 4,
  EstafetteManifest_FieldNumber_TriggersArray = 5,
  EstafetteManifest_FieldNumber_StagesArray = 6,
  EstafetteManifest_FieldNumber_ReleasesArray = 7,
};

@interface EstafetteManifest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) EstafetteBuilder *builder;
/** Test to see if @c builder has been set. */
@property(nonatomic, readwrite) BOOL hasBuilder;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *labels;
/** The number of items in @c labels without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger labels_Count;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteVersion *version;
/** Test to see if @c version has been set. */
@property(nonatomic, readwrite) BOOL hasVersion;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableDictionary<NSString*, NSString*> *globalEnvVars;
/** The number of items in @c globalEnvVars without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger globalEnvVars_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EstafetteTrigger*> *triggersArray;
/** The number of items in @c triggersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger triggersArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EstafetteStage*> *stagesArray;
/** The number of items in @c stagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger stagesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EstafetteRelease*> *releasesArray;
/** The number of items in @c releasesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger releasesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
