// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_event.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EstafetteCronEvent;
@class EstafetteDockerEvent;
@class EstafetteGitEvent;
@class EstafetteManualEvent;
@class EstafettePipelineEvent;
@class EstafettePubSubEvent;
@class EstafetteReleaseEvent;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EstafetteEventRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EstafetteEventRoot : GPBRootObject
@end

#pragma mark - EstafetteEvent

typedef GPB_ENUM(EstafetteEvent_FieldNumber) {
  EstafetteEvent_FieldNumber_Pipeline = 1,
  EstafetteEvent_FieldNumber_Release_p = 2,
  EstafetteEvent_FieldNumber_Git = 3,
  EstafetteEvent_FieldNumber_Docker = 4,
  EstafetteEvent_FieldNumber_Cron = 5,
  EstafetteEvent_FieldNumber_PubSub = 6,
  EstafetteEvent_FieldNumber_Manual = 7,
};

@interface EstafetteEvent : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) EstafettePipelineEvent *pipeline;
/** Test to see if @c pipeline has been set. */
@property(nonatomic, readwrite) BOOL hasPipeline;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteReleaseEvent *release_p;
/** Test to see if @c release_p has been set. */
@property(nonatomic, readwrite) BOOL hasRelease_p;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteGitEvent *git;
/** Test to see if @c git has been set. */
@property(nonatomic, readwrite) BOOL hasGit;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteDockerEvent *docker;
/** Test to see if @c docker has been set. */
@property(nonatomic, readwrite) BOOL hasDocker;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteCronEvent *cron;
/** Test to see if @c cron has been set. */
@property(nonatomic, readwrite) BOOL hasCron;

@property(nonatomic, readwrite, strong, null_resettable) EstafettePubSubEvent *pubSub;
/** Test to see if @c pubSub has been set. */
@property(nonatomic, readwrite) BOOL hasPubSub;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteManualEvent *manual;
/** Test to see if @c manual has been set. */
@property(nonatomic, readwrite) BOOL hasManual;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
