// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_version.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "manifest.v1/EstafetteVersion.pbobjc.h"
#import "manifest.v1/EstafetteCustomVersion.pbobjc.h"
#import "manifest.v1/EstafetteSemverVersion.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - EstafetteVersionRoot

@implementation EstafetteVersionRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - EstafetteVersionRoot_FileDescriptor

static GPBFileDescriptor *EstafetteVersionRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"manifest.v1"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - EstafetteVersion

@implementation EstafetteVersion

@dynamic hasSemver, semver;
@dynamic hasCustom, custom;

typedef struct EstafetteVersion__storage_ {
  uint32_t _has_storage_[1];
  EstafetteSemverVersion *semver;
  EstafetteCustomVersion *custom;
} EstafetteVersion__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "semver",
        .dataTypeSpecific.className = GPBStringifySymbol(EstafetteSemverVersion),
        .number = EstafetteVersion_FieldNumber_Semver,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(EstafetteVersion__storage_, semver),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "custom",
        .dataTypeSpecific.className = GPBStringifySymbol(EstafetteCustomVersion),
        .number = EstafetteVersion_FieldNumber_Custom,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(EstafetteVersion__storage_, custom),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[EstafetteVersion class]
                                     rootClass:[EstafetteVersionRoot class]
                                          file:EstafetteVersionRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(EstafetteVersion__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
