// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_release_event.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EstafetteReleaseEventRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EstafetteReleaseEventRoot : GPBRootObject
@end

#pragma mark - EstafetteReleaseEvent

typedef GPB_ENUM(EstafetteReleaseEvent_FieldNumber) {
  EstafetteReleaseEvent_FieldNumber_ReleaseVersion = 1,
  EstafetteReleaseEvent_FieldNumber_RepoSource = 2,
  EstafetteReleaseEvent_FieldNumber_RepoOwner = 3,
  EstafetteReleaseEvent_FieldNumber_RepoName = 4,
  EstafetteReleaseEvent_FieldNumber_Target = 5,
  EstafetteReleaseEvent_FieldNumber_Status = 6,
  EstafetteReleaseEvent_FieldNumber_Event = 7,
};

@interface EstafetteReleaseEvent : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *releaseVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *repoSource;

@property(nonatomic, readwrite, copy, null_resettable) NSString *repoOwner;

@property(nonatomic, readwrite, copy, null_resettable) NSString *repoName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *target;

@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

@property(nonatomic, readwrite, copy, null_resettable) NSString *event;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
