// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manifest.v1/estafette_trigger.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EstafetteCronTrigger;
@class EstafetteDockerTrigger;
@class EstafetteGitTrigger;
@class EstafettePipelineTrigger;
@class EstafettePubSubTrigger;
@class EstafetteReleaseTrigger;
@class EstafetteTriggerBuildAction;
@class EstafetteTriggerReleaseAction;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EstafetteTriggerRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EstafetteTriggerRoot : GPBRootObject
@end

#pragma mark - EstafetteTrigger

typedef GPB_ENUM(EstafetteTrigger_FieldNumber) {
  EstafetteTrigger_FieldNumber_Pipeline = 1,
  EstafetteTrigger_FieldNumber_Release_p = 2,
  EstafetteTrigger_FieldNumber_Git = 3,
  EstafetteTrigger_FieldNumber_Docker = 4,
  EstafetteTrigger_FieldNumber_Cron = 5,
  EstafetteTrigger_FieldNumber_PubSub = 6,
  EstafetteTrigger_FieldNumber_BuildAction = 7,
  EstafetteTrigger_FieldNumber_ReleaseAction = 8,
};

@interface EstafetteTrigger : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) EstafettePipelineTrigger *pipeline;
/** Test to see if @c pipeline has been set. */
@property(nonatomic, readwrite) BOOL hasPipeline;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteReleaseTrigger *release_p;
/** Test to see if @c release_p has been set. */
@property(nonatomic, readwrite) BOOL hasRelease_p;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteGitTrigger *git;
/** Test to see if @c git has been set. */
@property(nonatomic, readwrite) BOOL hasGit;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteDockerTrigger *docker;
/** Test to see if @c docker has been set. */
@property(nonatomic, readwrite) BOOL hasDocker;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteCronTrigger *cron;
/** Test to see if @c cron has been set. */
@property(nonatomic, readwrite) BOOL hasCron;

@property(nonatomic, readwrite, strong, null_resettable) EstafettePubSubTrigger *pubSub;
/** Test to see if @c pubSub has been set. */
@property(nonatomic, readwrite) BOOL hasPubSub;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteTriggerBuildAction *buildAction;
/** Test to see if @c buildAction has been set. */
@property(nonatomic, readwrite) BOOL hasBuildAction;

@property(nonatomic, readwrite, strong, null_resettable) EstafetteTriggerReleaseAction *releaseAction;
/** Test to see if @c releaseAction has been set. */
@property(nonatomic, readwrite) BOOL hasReleaseAction;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
